"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Clock3, LogOut, Settings, UserRound } from "lucide-react";

type SessionUser = { authenticated:true;display_name?:string;email?:string;plan?:{name:string;code:string};plan_status?:string;trial_ends_at?:string|null;usage?:{searches_today:number;search_limit:number|null} };
async function readSession():Promise<SessionUser|null>{try{const r=await fetch("/api/backend/api/v1/auth/session",{credentials:"include",cache:"no-store"});if(!r.ok)return null;const d=await r.json();return d?.authenticated?d as SessionUser:null}catch{return null}}
export default function AccountMenu(){const[user,setUser]=useState<SessionUser|null>(null);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{let alive=true;const sync=async()=>{const next=await readSession();if(!alive)return;setUser(next);setLoading(false);if(!next)setOpen(false)};void sync();const interval=window.setInterval(()=>{void sync()},5000);return()=>{alive=false;window.clearInterval(interval)}},[]);
 useEffect(()=>{if(!open)return;const onPointerDown=(event:MouseEvent)=>{if(ref.current&&!ref.current.contains(event.target as Node))setOpen(false)};document.addEventListener("mousedown",onPointerDown);return()=>document.removeEventListener("mousedown",onPointerDown)},[open]);
 async function signOut(){setBusy(true);setUser(null);setOpen(false);try{await fetch("/api/backend/api/v1/auth/logout",{method:"POST",credentials:"include",cache:"no-store"})}finally{window.location.replace("/login")}}
 if(loading||!user)return null;
 const trial=user.plan_status==="trialing";const limit=user.usage?.search_limit;const used=user.usage?.searches_today??0;
 return <div ref={ref} className="relative"><button type="button" onClick={()=>setOpen(v=>!v)} aria-label="Account menu" title="Account menu" className="flex h-8 w-8 items-center justify-center rounded-md border border-white/8 bg-[#070a0f]/90 text-white/40 backdrop-blur hover:bg-white/[.04] hover:text-white/80"><UserRound size={15}/></button>{open&&<div className="absolute right-0 top-10 z-[80] w-72 overflow-hidden rounded-xl border border-white/[.09] bg-[#0b0f16] shadow-2xl shadow-black/40"><div className="border-b border-white/[.07] px-4 py-3"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-semibold text-white/90">{user.display_name||"Account"}</div><div className="mt-0.5 truncate text-[10px] text-white/35">{user.email}</div></div><span className="shrink-0 rounded-full border border-amber-300/20 bg-amber-300/[.06] px-2 py-1 text-[9px] font-semibold text-amber-200">{user.plan?.name||"Free"}</span></div>{trial&&<div className="mt-3 flex items-center gap-1.5 text-[9px] text-amber-200/80"><Clock3 size={11}/> Trial active · ends {user.trial_ends_at?new Date(user.trial_ends_at).toLocaleDateString():"soon"}</div>}<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-amber-300" style={{width:limit?`${Math.min(100,(used/limit)*100)}%`:"0%"}}/></div><div className="mt-1 flex justify-between text-[9px] text-white/25"><span>Searches today</span><span>{used}{limit?` / ${limit}`:""}</span></div></div><div className="p-1.5"><Link href="/settings" onClick={()=>setOpen(false)} className="flex items-center gap-2.5 rounded-lg px-3 py-2.5 text-xs text-white/65 hover:bg-white/[.05] hover:text-white"><Settings size={14}/> Account settings</Link><button type="button" onClick={signOut} disabled={busy} className="flex w-full items-center gap-2.5 rounded-lg px-3 py-2.5 text-xs text-red-300/75 hover:bg-red-400/[.06] hover:text-red-200 disabled:opacity-50"><LogOut size={14}/> {busy?"Signing out…":"Sign out"}</button></div></div>}</div>;
}
