"use client";

import { FormEvent, useState } from "react";
import { ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";

const api=(path:string,init?:RequestInit)=>fetch(`/api/backend/api/v1/auth${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});

export default function LoginPage(){
  const router=useRouter(); const [register,setRegister]=useState(false); const [email,setEmail]=useState("demo-user@marketmemory.local"); const [password,setPassword]=useState("DemoUser@2026"); const [name,setName]=useState("Demo User"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const r=await api(register?"/register":"/login",{method:"POST",body:JSON.stringify({email,password,display_name:name})});const b=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setError(b.detail||"Unable to authenticate");return;}router.replace("/");router.refresh();}
  return <main className="min-h-screen bg-[#070a0f] text-white flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-sm rounded-xl border border-white/10 bg-[#0b1017] p-6 shadow-2xl"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-amber-300 text-black"><ShieldCheck size={18}/></div><div><div className="text-sm font-semibold">Market Memory</div><div className="text-[10px] text-white/35">{register?"Create your workspace account":"Sign in to your workspace"}</div></div></div>{register&&<label className="mt-6 block text-[10px] uppercase tracking-wider text-white/35">Name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-black/20 px-3 text-xs outline-none"/></label>}<label className={`${register?"mt-3":"mt-6"} block text-[10px] uppercase tracking-wider text-white/35`}>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" className="mt-1 h-10 w-full rounded-md border border-white/10 bg-black/20 px-3 text-xs outline-none"/></label><label className="mt-3 block text-[10px] uppercase tracking-wider text-white/35">Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete={register?"new-password":"current-password"} className="mt-1 h-10 w-full rounded-md border border-white/10 bg-black/20 px-3 text-xs outline-none"/></label>{error&&<div className="mt-3 rounded-md border border-red-400/15 bg-red-400/5 p-2 text-[10px] text-red-200">{error}</div>}<button disabled={busy} className="mt-5 h-10 w-full rounded-md bg-amber-300 text-xs font-bold text-black disabled:opacity-50">{busy?"Working…":register?"Create account":"Sign in"}</button><button type="button" onClick={()=>setRegister(v=>!v)} className="mt-3 w-full text-[10px] text-white/35 hover:text-white/60">{register?"Already have an account? Sign in":"Need an account? Create one"}</button>{!register&&<div className="mt-4 rounded-md border border-amber-300/10 bg-amber-300/[.03] p-2 text-[9px] leading-4 text-white/30">Development test account: demo-user@marketmemory.local / DemoUser@2026</div>}</form></main>;
}
