"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Mail, ShieldCheck, LockKeyhole, CreditCard, LogOut } from "lucide-react";

const api=(path:string,init?:RequestInit)=>fetch(`/api/backend/api/v1/auth${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});
type User={id:number;email:string;first_name:string;last_name:string;display_name:string;plan:any;roles:any[];created_at:string|null};
type Plan={id:number;code:string;name:string;description:string;price_cents:number;active:boolean};
const money=(c:number)=>c>0?`₹${(c/100).toFixed(0)}/month`:"Free";
const rank=(code?:string)=>({free:0,basic:1,pro:2,enterprise:3}[code||""]??0);

export default function SettingsPage(){
 const [user,setUser]=useState<User|null>(null);const [plans,setPlans]=useState<Plan[]>([]);const [first,setFirst]=useState("");const [last,setLast]=useState("");const [current,setCurrent]=useState("");const [next,setNext]=useState("");const [confirm,setConfirm]=useState("");const [busy,setBusy]=useState(false);const [passwordBusy,setPasswordBusy]=useState(false);const [logoutBusy,setLogoutBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [upgradeMessage,setUpgradeMessage]=useState("");
 async function load(){const [u,p]=await Promise.all([api("/me"),api("/plans")]);if(u.ok){const b=await u.json();setUser(b);setFirst(b.first_name||"");setLast(b.last_name||"")}if(p.ok)setPlans(await p.json())}
 useEffect(()=>{void load()},[]);
 async function saveProfile(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");setError("");const r=await api("/profile",{method:"PATCH",body:JSON.stringify({first_name:first,last_name:last})});const b=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setError(b.detail||"Unable to update profile");return}setUser(b);setMessage("Profile updated");}
 async function changePassword(e:FormEvent){e.preventDefault();setPasswordBusy(true);setMessage("");setError("");if(next!==confirm){setError("New passwords do not match");setPasswordBusy(false);return}const r=await api("/password",{method:"POST",body:JSON.stringify({current_password:current,new_password:next})});const b=await r.json().catch(()=>({}));setPasswordBusy(false);if(!r.ok){setError(b.detail||"Unable to change password");return}setCurrent("");setNext("");setConfirm("");setUser(b);setMessage("Password changed successfully");}
 async function signOut(){setLogoutBusy(true);try{await api("/logout",{method:"POST"})}finally{window.location.replace("/login");}}
 if(!user)return <main className="min-h-screen bg-[#070a0f] text-white flex items-center justify-center text-xs text-white/30">Loading account…</main>;
 const currentPlan=user.plan;const upgradePlans=plans.filter(p=>p.code!==currentPlan?.code&&rank(p.code)>rank(currentPlan?.code)).sort((a,b)=>rank(a.code)-rank(b.code));const initials=(first||last||user.email).slice(0,1).toUpperCase();
 return <main className="min-h-screen bg-[#070a0f] text-white"><header className="border-b border-white/[.07] bg-[#080c12]"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-5"><div className="flex items-center gap-3"><Link href="/dashboard" className="flex h-8 w-8 items-center justify-center rounded-lg border border-white/10 bg-white/[.03] text-white/50 hover:text-white">←</Link><div><div className="text-sm font-semibold">Account settings</div><div className="text-[10px] text-white/30">Manage your profile, security and plan</div></div></div><div className="flex items-center gap-3"><Link href="/dashboard" className="text-[10px] text-white/40 hover:text-white">Back to Market Memory</Link><button type="button" onClick={signOut} disabled={logoutBusy} className="flex h-8 items-center gap-1.5 rounded-lg border border-red-400/15 bg-red-400/[.04] px-3 text-[10px] font-semibold text-red-300/80 hover:bg-red-400/[.08] hover:text-red-200 disabled:opacity-50"><LogOut size={13}/>{logoutBusy?"Signing out…":"Sign out"}</button></div></div></header>
 <div className="mx-auto max-w-5xl space-y-4 p-5 sm:p-8">
  <section className="panel overflow-hidden"><div className="border-b border-white/[.06] bg-white/[.015] p-5"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl border border-amber-300/20 bg-amber-300/[.08] text-lg font-semibold text-amber-100">{initials}</div><div><div className="text-lg font-semibold">{user.display_name||"Your profile"}</div><div className="mt-1 flex items-center gap-1.5 text-[11px] text-white/35"><Mail size={12}/>{user.email}</div></div><span className="ml-auto rounded-full border border-emerald-400/15 bg-emerald-400/[.05] px-2.5 py-1 text-[8px] font-semibold uppercase tracking-wider text-emerald-300/70">{user.status}</span></div></div>
   <form onSubmit={saveProfile} className="p-5 sm:p-6"><div className="mb-4"><div className="text-xs font-semibold">Personal information</div><div className="mt-1 text-[10px] text-white/30">Your registered email is your account identifier and cannot be changed here.</div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="First name"><input value={first} onChange={e=>setFirst(e.target.value)} className="input" placeholder="First name"/></Field><Field label="Last name"><input value={last} onChange={e=>setLast(e.target.value)} className="input" placeholder="Last name"/></Field><Field label="Registered email"><input value={user.email} disabled className="input cursor-not-allowed opacity-55 sm:col-span-2"/></Field></div><div className="mt-5 flex flex-wrap items-center gap-3"><button disabled={busy} className="primary-button h-10 px-5 disabled:opacity-40">{busy?"Saving…":"Save profile"}</button>{message&&<span className="flex items-center gap-1.5 text-[10px] text-emerald-300/70"><CheckCircle2 size={13}/>{message}</span>}{error&&<span className="text-[10px] text-red-300/80">{error}</span>}</div></form>
  </section>
  <section className="grid gap-4 lg:grid-cols-[1fr_1.1fr]"><div className="panel p-5"><div className="flex items-center gap-2"><div className="icon-box"><LockKeyhole size={15}/></div><div><div className="text-xs font-semibold">Password & security</div><div className="mt-1 text-[10px] text-white/30">Change your password securely.</div></div></div><form onSubmit={changePassword} className="mt-5 space-y-3"><Field label="Current password"><input required value={current} onChange={e=>setCurrent(e.target.value)} type="password" autoComplete="current-password" className="input"/></Field><Field label="New password"><input required minLength={8} value={next} onChange={e=>setNext(e.target.value)} type="password" autoComplete="new-password" className="input"/></Field><Field label="Confirm new password"><input required minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} type="password" autoComplete="new-password" className="input"/></Field><button disabled={passwordBusy} className="primary-button h-10 w-full disabled:opacity-40">{passwordBusy?"Updating…":"Change password"}</button></form></div>
   <div className="panel p-5"><div className="flex items-center gap-2"><div className="icon-box"><CreditCard size={15}/></div><div><div className="text-xs font-semibold">Your plan</div><div className="mt-1 text-[10px] text-white/30">Current subscription and available higher tiers.</div></div></div><div className="mt-5 rounded-xl border border-amber-300/15 bg-amber-300/[.04] p-4"><div className="flex items-start justify-between"><div><div className="text-sm font-semibold">{currentPlan?.name||"No plan"}</div><div className="mt-1 text-[10px] text-white/35">{currentPlan?.description||"No active plan assigned."}</div></div><span className="font-mono text-xs text-amber-100/70">{currentPlan?money(currentPlan.price_cents):"—"}</span></div></div><div className="mt-4 space-y-2">{upgradePlans.length?upgradePlans.map(p=><div key={p.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/[.07] bg-white/[.015] p-3"><div><div className="text-[11px] font-semibold">{p.name}</div><div className="mt-1 text-[9px] text-white/25">{p.description} · {money(p.price_cents)}</div></div><button type="button" onClick={()=>setUpgradeMessage(`Upgrade to ${p.name} will open checkout once billing is enabled.`)} className="flex shrink-0 items-center gap-1 rounded-lg border border-amber-300/20 bg-amber-300/[.06] px-3 py-2 text-[9px] font-semibold text-amber-100/75 hover:bg-amber-300/[.10]">Upgrade <ArrowRight size={12}/></button></div>):<div className="rounded-lg border border-white/[.05] p-3 text-[9px] text-white/25">You are already on the highest available tier.</div>}{upgradeMessage&&<div className="mt-3 rounded-lg border border-amber-300/10 bg-amber-300/[.03] p-3 text-[9px] leading-4 text-amber-100/55">{upgradeMessage}</div>}<div className="mt-3 rounded-lg border border-white/[.05] p-3 text-[9px] leading-4 text-white/25">Plan checkout is not connected yet. Until billing is enabled, an upgrade does not change your entitlement.</div></div></div></section>
  <section className="panel p-5"><div className="flex items-center gap-3"><ShieldCheck size={16} className="text-emerald-300/65"/><div><div className="text-xs font-semibold">Account access</div><div className="mt-1 text-[10px] text-white/30">Your enabled modules are controlled by your assigned roles and permissions.</div></div></div><div className="mt-4 flex flex-wrap gap-2">{user.roles?.map(r=><span key={r.id} className="rounded-full border border-white/10 bg-white/[.025] px-3 py-1.5 text-[9px] text-white/45">{r.name}</span>)}{!user.roles?.length&&<span className="text-[10px] text-white/25">Standard account access</span>}</div></section>
  <section className="rounded-xl border border-red-400/10 bg-red-400/[.025] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-semibold text-white/75">Sign out of Market Memory</div><div className="mt-1 text-[10px] text-white/30">End your current session on this device.</div></div><button type="button" onClick={signOut} disabled={logoutBusy} className="flex h-9 items-center gap-1.5 rounded-lg border border-red-400/15 px-4 text-[10px] font-semibold text-red-300/80 hover:bg-red-400/[.06] disabled:opacity-50"><LogOut size={13}/>{logoutBusy?"Signing out…":"Sign out"}</button></div></section>
 </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[9px] font-semibold uppercase tracking-[.12em] text-white/30">{label}</span>{children}</label>}
