"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, Check, ChevronRight, CircleUserRound, Database, KeyRound, LayoutDashboard, LogOut, ShieldCheck, Users, X } from "lucide-react";

type Tab = "overview" | "users" | "roles" | "plans" | "modules" | "audit";
type User = { id:number; email:string; display_name:string; status:string; plan:any; roles:any[]; permissions:string[]; modules:Record<string,boolean>; access_version:number; last_seen_at:string|null; created_at:string };
type Role = { id:number; code:string; name:string; description:string; system:boolean; user_count:number; permission_codes:string[] };
type Permission = { id:number; code:string; module:string; operation:string; description:string };

const tabs: {id:Tab; label:string; icon:any}[] = [
  {id:"overview",label:"Overview",icon:LayoutDashboard},{id:"users",label:"Users",icon:Users},{id:"roles",label:"Roles & Rights",icon:KeyRound},{id:"plans",label:"Plans",icon:CircleUserRound},{id:"modules",label:"Modules & Operations",icon:Database},{id:"audit",label:"Audit Log",icon:Activity},
];
const api = (path:string, init?:RequestInit) => fetch(`/api/backend/api/v1/admin${path}`, { ...init, credentials:"include", headers:{"Content-Type":"application/json", ...(init?.headers||{})}, cache:"no-store" });
const fmtDate = (v:string|null) => v ? new Date(v).toLocaleString() : "Never";

export default function AdminPage() {
  const [authenticated,setAuthenticated]=useState<boolean|null>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [loginError,setLoginError]=useState(""); const [tab,setTab]=useState<Tab>("overview"); const [collapsed,setCollapsed]=useState(false);
  const [overview,setOverview]=useState<any>(null); const [users,setUsers]=useState<User[]>([]); const [roles,setRoles]=useState<Role[]>([]); const [permissions,setPermissions]=useState<Permission[]>([]); const [plans,setPlans]=useState<any[]>([]); const [audit,setAudit]=useState<any[]>([]); const [selected,setSelected]=useState<User|null>(null); const [query,setQuery]=useState(""); const [saving,setSaving]=useState(false);

  async function checkSession(){ const r=await api("/session"); const b=await r.json().catch(()=>({})); setAuthenticated(b.authenticated===true); if(b.authenticated) setEmail(b.email||""); }
  async function login(e:React.FormEvent){ e.preventDefault(); setLoginError(""); const r=await api("/login",{method:"POST",body:JSON.stringify({email,password})}); const b=await r.json().catch(()=>({})); if(!r.ok){setLoginError(b.detail||"Login failed");return;} setAuthenticated(true); setPassword(""); }
  async function load(){ if(!authenticated)return; const [o,u,r,p,a,m]=await Promise.all([api("/overview"),api(`/users?q=${encodeURIComponent(query)}`),api("/roles"),api("/plans"),api("/audit"),api("/permissions")]); setOverview(await o.json()); setUsers(await u.json()); setRoles(await r.json()); setPlans(await p.json()); setAudit(await a.json()); setPermissions(await m.json()); }
  useEffect(()=>{void checkSession()},[]); useEffect(()=>{void load()},[authenticated,query]);
  async function saveUser(patch:any){ if(!selected)return; setSaving(true); const r=await api(`/users/${selected.id}`,{method:"PATCH",body:JSON.stringify(patch)}); const b=await r.json(); setSaving(false); if(r.ok){setSelected(b); setUsers(v=>v.map(x=>x.id===b.id?b:x));} }
  async function saveRole(role:Role, code:string, enabled:boolean){ const next=enabled?[...new Set([...role.permission_codes,code])]:role.permission_codes.filter(x=>x!==code); await api(`/roles/${role.id}`,{method:"PATCH",body:JSON.stringify({permission_codes:next})}); setRoles(v=>v.map(r=>r.id===role.id?{...r,permission_codes:next}:r)); }
  async function logout(){await api("/logout",{method:"POST"});setAuthenticated(false);setSelected(null);}

  if(authenticated===null) return <div className="min-h-screen bg-[#070a0f]"/>;
  if(!authenticated) return <main className="min-h-screen bg-[#070a0f] text-white flex items-center justify-center p-6"><form onSubmit={login} className="w-full max-w-sm rounded-xl border border-white/10 bg-[#0b1017] p-6 shadow-2xl"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-amber-300 text-black"><ShieldCheck size={18}/></div><div><div className="text-sm font-semibold">Owner Control</div><div className="text-[10px] text-white/35">Restricted system administration</div></div></div><label className="mt-6 block text-[10px] uppercase tracking-wider text-white/35">Owner email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="username" className="mt-1 h-10 w-full rounded-md border border-white/10 bg-black/20 px-3 text-xs outline-none focus:border-amber-300/40"/></label><label className="mt-3 block text-[10px] uppercase tracking-wider text-white/35">Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" className="mt-1 h-10 w-full rounded-md border border-white/10 bg-black/20 px-3 text-xs outline-none focus:border-amber-300/40"/></label>{loginError&&<div className="mt-3 rounded-md border border-red-400/15 bg-red-400/5 p-2 text-[10px] text-red-200">{loginError}</div>}<button className="mt-5 h-10 w-full rounded-md bg-amber-300 text-xs font-bold text-black">Enter owner control</button><div className="mt-4 text-[9px] leading-4 text-white/25">This area is intentionally absent from the normal workspace until an owner session is authenticated.</div></form></main>;

  const moduleGroups = Object.entries(permissions.reduce((acc:any,p)=>{(acc[p.module]??=[]).push(p);return acc},{} as Record<string,Permission[]>));
  return <main className="min-h-screen bg-[#070a0f] text-white"><header className="sticky top-0 z-40 flex h-12 items-center justify-between border-b border-white/8 bg-[#070a0f]/95 px-4 backdrop-blur"><div className="flex items-center gap-2.5"><div className="flex h-7 w-7 items-center justify-center rounded-md bg-amber-300 text-black"><ShieldCheck size={15}/></div><span className="text-xs font-semibold tracking-[.12em]">OWNER CONTROL</span><span className="hidden rounded border border-amber-300/15 bg-amber-300/5 px-2 py-1 text-[8px] uppercase tracking-wider text-amber-200/60 sm:inline">Full authority</span></div><div className="flex items-center gap-3 text-[9px] text-white/35"><span>{email}</span><button onClick={logout} className="flex items-center gap-1 rounded px-2 py-1.5 hover:bg-white/5"><LogOut size={12}/>Sign out</button></div></header>
    <div className="flex min-h-[calc(100vh-48px)]"><aside className={`${collapsed?"w-14":"w-52"} shrink-0 border-r border-white/7 bg-[#090d13] p-2 transition-all`}><div className="mb-3 flex items-center justify-between px-2 py-2"><span className={`${collapsed?"hidden":""} text-[9px] font-semibold uppercase tracking-wider text-white/25`}>Admin</span><button onClick={()=>setCollapsed(!collapsed)} className="rounded p-1 text-white/30 hover:bg-white/5">{collapsed?<ChevronRight size={13}/>:<X size={13}/>}</button></div>{tabs.map(t=>{const I=t.icon;return <button key={t.id} onClick={()=>setTab(t.id)} className={`mb-1 flex w-full items-center gap-2 rounded-md px-2.5 py-2 text-[10px] ${tab===t.id?"bg-amber-300/10 text-amber-100":"text-white/45 hover:bg-white/5"} ${collapsed?"justify-center":""}`} title={collapsed?t.label:undefined}><I size={14}/>{!collapsed&&t.label}</button>})}</aside>
      <section className="min-w-0 flex-1 p-4 sm:p-6"><div className="mx-auto max-w-[1500px]">{tab==="overview"&&<Overview data={overview}/>} {tab==="users"&&<UsersView users={users} query={query} setQuery={setQuery} selected={selected} setSelected={setSelected} roles={roles} plans={plans} saveUser={saveUser} saving={saving}/>} {tab==="roles"&&<RolesView roles={roles} permissions={permissions} saveRole={saveRole}/>} {tab==="plans"&&<PlansView plans={plans} onRefresh={load}/>} {tab==="modules"&&<ModulesView groups={moduleGroups}/>} {tab==="audit"&&<AuditView rows={audit}/>}</div></section></div></main>;
}

function Overview({data}:{data:any}){if(!data)return <Loading/>;return <><Title icon={LayoutDashboard} title="System overview" sub="Owner-level visibility across the platform."/><div className="grid gap-3 md:grid-cols-4">{[["Users",data.users,Users],["Active",data.active_users,Activity],["New · 24h",data.new_users_24h,BarChart3],["Returning · 7d",data.returning_users_7d,Users]].map(([l,v,I]:any)=><div className="panel p-4" key={l}><I size={14} className="text-amber-200/60"/><div className="mt-3 text-2xl font-semibold">{v}</div><div className="text-[9px] uppercase tracking-wider text-white/25">{l}</div></div>)}</div><div className="mt-3 grid gap-3 lg:grid-cols-2"><div className="panel p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-white/45">Usage · last 24h</div><div className="mt-3 text-2xl font-semibold">{Math.round((data.time_spent_ms_24h||0)/60000)} min</div><div className="mt-1 text-[10px] text-white/30">{data.events_24h} tracked events</div></div><div className="panel p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-white/45">Most used modules · 7d</div><div className="mt-3 space-y-2">{data.top_modules?.length?data.top_modules.map((x:any)=><div key={x.module} className="flex items-center justify-between border-b border-white/5 pb-2 text-[10px]"><span className="text-white/55">{x.module}</span><span className="font-mono text-white/35">{x.count}</span></div>):<div className="text-[10px] text-white/25">Usage events will appear here once authenticated user telemetry is connected.</div>}</div></div></div></>}

function UsersView({users,query,setQuery,selected,setSelected,roles,plans,saveUser,saving}:{users:User[];query:string;setQuery:(v:string)=>void;selected:User|null;setSelected:(v:User|null)=>void;roles:Role[];plans:any[];saveUser:(v:any)=>Promise<void>;saving:boolean}){return <><Title icon={Users} title="Users" sub="Every account, entitlement, role and module override in one place."/><div className="mb-3 flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email…" className="h-9 w-full max-w-md rounded-md border border-white/10 bg-[#0b1017] px-3 text-[10px] outline-none"/></div><div className="grid gap-3 lg:grid-cols-[1fr_430px]"><div className="panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-[10px]"><thead className="bg-white/[.02] text-[8px] uppercase tracking-wider text-white/25"><tr><th className="p-3">User</th><th>Status</th><th>Plan</th><th>Roles</th><th>Last seen</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id} onClick={()=>setSelected(u)} className={`cursor-pointer border-t border-white/5 hover:bg-white/[.025] ${selected?.id===u.id?"bg-amber-300/[.04]":""}`}><td className="p-3"><div className="font-medium text-white/70">{u.display_name||"Unnamed"}</div><div className="mt-0.5 text-[9px] text-white/30">{u.email}</div></td><td className="text-white/45">{u.status}</td><td className="text-white/45">{u.plan?.name||"—"}</td><td className="text-white/45">{u.roles.map(r=>r.name).join(", ")||"—"}</td><td className="text-white/30">{fmtDate(u.last_seen_at)}</td><td className="pr-3 text-right"><ChevronRight size={13} className="text-white/20"/></td></tr>)}</tbody></table>{!users.length&&<div className="p-8 text-center text-[10px] text-white/25">No users yet. Create accounts when the authentication layer is connected.</div>}</div></div>{selected?<UserDetail user={selected} roles={roles} plans={plans} saveUser={saveUser} saving={saving}/>:<div className="panel flex min-h-[350px] items-center justify-center p-6 text-center text-[10px] text-white/25">Select a user to manage plan, status, roles, direct rights and module visibility.</div>}</div></>}

function UserDetail({user,roles,plans,saveUser,saving}:{user:User;roles:Role[];plans:any[];saveUser:(v:any)=>Promise<void>;saving:boolean}){const [roleIds,setRoleIds]=useState(user.roles.map(r=>r.id)); const [plan,setPlan]=useState(user.plan?.id??""); const [status,setStatus]=useState(user.status); const [modules,setModules]=useState(user.modules||{}); const rolePermissions=useMemo(()=>new Set(roles.filter(r=>roleIds.includes(r.id)).flatMap(r=>r.permission_codes)),[roles,roleIds]); const [direct,setDirect]=useState(user.permissions.filter(p=>!rolePermissions.has(p))); useEffect(()=>{setRoleIds(user.roles.map(r=>r.id));setPlan(user.plan?.id??"");setStatus(user.status);setModules(user.modules||{});setDirect(user.permissions)},[user.id,user.access_version]);return <div className="panel p-4"><div className="flex items-start justify-between"><div><div className="text-sm font-semibold">{user.display_name||"Unnamed user"}</div><div className="text-[9px] text-white/30">{user.email}</div></div><span className="rounded border border-white/8 px-2 py-1 text-[8px] font-mono text-white/30">v{user.access_version}</span></div><div className="mt-5 space-y-4"><Field label="Status"><select value={status} onChange={e=>setStatus(e.target.value)} className="select"><option>active</option><option>disabled</option><option>suspended</option></select></Field><Field label="Plan"><select value={plan} onChange={e=>setPlan(e.target.value?Number(e.target.value):"")} className="select"><option value="">No plan</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Roles"><div className="space-y-1">{roles.map(r=><label key={r.id} className="flex items-center gap-2 rounded border border-white/6 p-2 text-[9px] text-white/50"><input type="checkbox" checked={roleIds.includes(r.id)} onChange={e=>setRoleIds(v=>e.target.checked?[...v,r.id]:v.filter(x=>x!==r.id))}/>{r.name}<span className="ml-auto text-white/20">{r.code}</span></label>)}</div></Field><Field label="Module visibility"><div className="grid grid-cols-2 gap-1">{["market_memory","pattern_quality","scanner","alerts","replay","evaluation","validation","favorites"].map(m=><label key={m} className="flex items-center gap-2 rounded border border-white/6 p-2 text-[8px] text-white/45"><input type="checkbox" checked={modules[m]===true} onChange={e=>setModules(v=>({...v,[m]:e.target.checked}))}/>{m.replaceAll("_"," ")}</label>)}</div></Field><button disabled={saving} onClick={()=>void saveUser({status,plan_id:plan||null,role_ids:roleIds,modules,permission_codes:direct})} className="h-9 w-full rounded-md bg-amber-300 text-[10px] font-bold text-black disabled:opacity-40">{saving?"Saving…":"Apply access changes immediately"}</button></div></div>}

function RolesView({roles,permissions,saveRole}:{roles:Role[];permissions:Permission[];saveRole:(r:Role,c:string,e:boolean)=>Promise<void>}){return <><Title icon={KeyRound} title="Roles & rights" sub="One transparent operation matrix. No hidden composite permissions."/><div className="panel overflow-hidden"><div className="overflow-auto"><table className="w-full min-w-[900px] text-left text-[9px]"><thead className="bg-white/[.02] text-[8px] uppercase tracking-wider text-white/25"><tr><th className="sticky left-0 bg-[#0b1017] p-3">Module / operation</th>{roles.map(r=><th key={r.id} className="p-3 text-center"><div>{r.name}</div><div className="mt-1 font-mono text-[7px] text-white/20">{r.code}</div></th>)}</tr></thead><tbody>{permissions.map(p=><tr key={p.code} className="border-t border-white/5"><td className="sticky left-0 bg-[#0b1017] p-3"><div className="text-white/55">{p.module}</div><div className="mt-0.5 font-mono text-white/25">{p.operation}</div></td>{roles.map(r=>{const on=r.permission_codes.includes(p.code);return <td key={r.id} className="p-2 text-center"><input type="checkbox" disabled={r.system&&r.code==="owner"} checked={on} onChange={e=>void saveRole(r,p.code,e.target.checked)} title={p.code}/></td>})}</tr>)}</tbody></table></div></div></>}

function PlansView({plans,onRefresh}:{plans:any[];onRefresh:()=>Promise<void>}){return <><Title icon={CircleUserRound} title="Plans" sub="Plans are modeled now so billing/entitlements can be connected later without redesigning access control."/><div className="grid gap-3 md:grid-cols-3">{plans.map(p=><div className="panel p-4" key={p.id}><div className="flex justify-between"><div className="font-semibold text-white/70">{p.name}</div><span className="text-[8px] text-emerald-300/60">{p.active?"ACTIVE":"OFF"}</span></div><div className="mt-2 font-mono text-[9px] text-white/25">{p.code}</div><div className="mt-5 text-lg font-semibold">{p.price_cents?`₹${(p.price_cents/100).toFixed(0)}`:"Free / not priced"}</div><div className="mt-1 text-[9px] text-white/30">{p.description}</div></div>)}</div></>}
function ModulesView({groups}:{groups:[string,Permission[]][]}){return <><Title icon={Database} title="Modules & operations" sub="The complete permission vocabulary used by the platform."/><div className="space-y-2">{groups.map(([m,items])=><div className="panel p-4" key={m}><div className="text-[10px] font-semibold uppercase tracking-wider text-white/50">{m.replaceAll("_"," ")}</div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map(p=><div key={p.code} className="rounded border border-white/6 p-3"><div className="font-mono text-[9px] text-white/55">{p.operation}</div><div className="mt-1 text-[9px] text-white/25">{p.description}</div></div>)}</div></div>)}</div></>}
function AuditView({rows}:{rows:any[]}){return <><Title icon={Activity} title="Audit log" sub="Administrative changes are recorded with actor, target and metadata."/><div className="panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-[9px]"><thead className="bg-white/[.02] text-[8px] uppercase tracking-wider text-white/25"><tr><th className="p-3">Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Metadata</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t border-white/5"><td className="p-3 text-white/30">{fmtDate(x.created_at)}</td><td className="text-white/45">{x.actor_email}</td><td className="font-mono text-amber-200/55">{x.action}</td><td className="text-white/35">{x.target_type}:{x.target_id}</td><td className="max-w-[300px] truncate font-mono text-white/20">{JSON.stringify(x.metadata)}</td></tr>)}</tbody></table></div></div></>}
function Title({icon:Icon,title,sub}:{icon:any;title:string;sub:string}){return <div className="mb-5"><div className="flex items-center gap-2 text-[18px] font-semibold"><Icon size={18} className="text-amber-200/65"/>{title}</div><div className="mt-1 text-[10px] text-white/30">{sub}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><div className="mb-1 text-[8px] font-semibold uppercase tracking-wider text-white/25">{label}</div>{children}</div>}
function Loading(){return <div className="flex min-h-[50vh] items-center justify-center text-[10px] text-white/25">Loading owner control…</div>}
